services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gateway:
    build: 
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - consul
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

  user-service:
    build: 
      context: .
      dockerfile: src/Services/UserService/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5001

  product-service:
    build: 
      context: .
      dockerfile: src/Services/ProductService/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5002

  order-service:
    build: 
      context: .
      dockerfile: src/Services/OrderService/Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5003

  notification-service:
    build: 
      context: .
      dockerfile: src/Services/NotificationService/Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5004

volumes:
  postgres_data: