version: '3.8'

services:
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: consul agent -dev -client=0.0.0.0 -ui

  gateway:
    build: 
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - consul
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

  user-service:
    build: 
      context: .
      dockerfile: Services/UserService/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001

  product-service:
    build: 
      context: .
      dockerfile: Services/ProductService/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002

  order-service:
    build: 
      context: .
      dockerfile: Services/OrderService/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003

  notification-service:
    build: 
      context: .
      dockerfile: Services/NotificationService/Dockerfile
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5004